### ISSUE TITLE
Research PostgresOL

### ISSUE THREAD

**Issue by carlymclift** [GreysonElkins/exquisite-corpse#9]
Spend time researching the docs for PostgresQL and any other back end technologies that we will need

**Comment by GreysonElkins** [comment]
* [PostgreSQL command line cheatsheet](https://gist.github.com/Kartones/dd3ff5ec5ea238d4c546)
* [A schema planning tool](https://ondras.zarovi.cz/sql/demo/)
* ![image](https://user-images.githubusercontent.com/62047446/92673913-7bf99280-f2d9-11ea-9226-644992a97703.png)
